### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by sikofitt** [leewoodridge/RenegadeBBS#1]
I was just thinking it might be useful to enable the discussion board for the repo?

What do you think?

**Comment by Renegade-Exodus** [comment]
Yeah ... was thinking of setting something up on the BBS to be a bit more
private, but yeah that works too.

**Comment by sikofitt** [comment]
I haven't used the discussion feature before. We might be able to make it private.

**Comment by sikofitt** [comment]
Can we do both?  I don't have access to enable the discussions feature on here though.

**Comment by Renegade-Exodus** [comment]
Sure.  I'll make a base tonight.  No problem

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Renegade-Exodus** [comment]
Base setup ... sent emails to you both showing where it is. :)

**Comment by sikofitt** [comment]
Awesome! I'll check in tonight.
